
export const FETCH_DATA_REQUEST='FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS='FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE='FETCH_DATA_FAILURE';

export const FETCH_DATA_REQUEST1='FETCH_DATA_REQUEST1';
export const FETCH_DATA_SUCCESS1='FETCH_DATA_SUCCESS1';
export const FETCH_DATA_FAILURE1='FETCH_DATA_FAILURE1';

export const FETCH_DATA_REQUEST2='FETCH_DATA_REQUEST2';
export const FETCH_DATA_SUCCESS2='FETCH_DATA_SUCCESS2';
export const FETCH_DATA_FAILURE2='FETCH_DATA_FAILURE2';

export const FETCH_DATA_REQUEST3='FETCH_DATA_REQUEST3';
export const FETCH_DATA_SUCCESS3='FETCH_DATA_SUCCESS3';
export const FETCH_DATA_FAILURE3='FETCH_DATA_FAILURE3';

export const FETCH_DATA_REQUEST4='FETCH_DATA_REQUEST4';
export const FETCH_DATA_SUCCESS4='FETCH_DATA_SUCCESS4';
export const FETCH_DATA_FAILURE4='FETCH_DATA_FAILURE4';

export const FETCH_DATA_REQUEST5='FETCH_DATA_REQUEST5';
export const FETCH_DATA_SUCCESS5='FETCH_DATA_SUCCESS5';
export const FETCH_DATA_FAILURE5='FETCH_DATA_FAILURE5';

export const FETCH_DATA_REQUEST6='FETCH_DATA_REQUEST6';
export const FETCH_DATA_SUCCESS6='FETCH_DATA_SUCCESS6';
export const FETCH_DATA_FAILURE6='FETCH_DATA_FAILURE6';

export const GET_SSINGLE_PRODUCT_REQUEST="GET_SSINGLE_PRODUCT_REQUEST";
export const GET_SSINGLE_PRODUCT_SUCCESS="GET_SSINGLE_PRODUCT_SUCCESS";
export const GET_SSINGLE_PRODUCT_FAILURE="GET_SSINGLE_PRODUCT_FAILURE";

export const GET_SSINGLE_PRODUCT_REQUEST1="GET_SSINGLE_PRODUCT_REQUEST1";
export const GET_SSINGLE_PRODUCT_SUCCESS1="GET_SSINGLE_PRODUCT_SUCCESS1";
export const GET_SSINGLE_PRODUCT_FAILURE1="GET_SSINGLE_PRODUCT_FAILURE1";


export const GET_SSINGLE_PRODUCT_REQUEST2="GET_SSINGLE_PRODUCT_REQUEST2";
export const GET_SSINGLE_PRODUCT_SUCCESS2="GET_SSINGLE_PRODUCT_SUCCESS2";
export const GET_SSINGLE_PRODUCT_FAILURE2="GET_SSINGLE_PRODUCT_FAILURE2";

export const GET_SSINGLE_PRODUCT_REQUEST3="GET_SSINGLE_PRODUCT_REQUEST3";
export const GET_SSINGLE_PRODUCT_SUCCESS3="GET_SSINGLE_PRODUCT_SUCCESS3";
export const GET_SSINGLE_PRODUCT_FAILURE3="GET_SSINGLE_PRODUCT_FAILURE3";

export const GET_SSINGLE_PRODUCT_REQUEST4="GET_SSINGLE_PRODUCT_REQUEST4";
export const GET_SSINGLE_PRODUCT_SUCCESS4="GET_SSINGLE_PRODUCT_SUCCESS4";
export const GET_SSINGLE_PRODUCT_FAILURE4="GET_SSINGLE_PRODUCT_FAILURE4";

export const GET_SSINGLE_PRODUCT_REQUEST5="GET_SSINGLE_PRODUCT_REQUEST5";
export const GET_SSINGLE_PRODUCT_SUCCESS5="GET_SSINGLE_PRODUCT_SUCCESS5";
export const GET_SSINGLE_PRODUCT_FAILURE5="GET_SSINGLE_PRODUCT_FAILURE5";

export const GET_SSINGLE_PRODUCT_REQUEST6="GET_SSINGLE_PRODUCT_REQUEST6";
export const GET_SSINGLE_PRODUCT_SUCCESS6="GET_SSINGLE_PRODUCT_SUCCESS6";
export const GET_SSINGLE_PRODUCT_FAILURE6="GET_SSINGLE_PRODUCT_FAILURE6";

export const ADD_PRODUCT_CART_REQUEST="ADD_PRODUCT_CART_REQUEST";
export const ADD_PRODUCT_CART_SUCCESS="ADD_PRODUCT_CART_SUCCESS";
export const ADD_PRODUCT_CART_FAILURE="ADD_PRODUCT_CART_FAILURE";

export const FETCH_CART_REQUEST="FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS="FETCH_CART_SUCCESS";
export const FETCH_CART_FAILURE="FETCH_CART_FAILURE";

export const REMOVE_PRODUCT_CART_REQUEST="REMOVE_PRODUCT_CART_REQUEST";
export const REMOVE_PRODUCT_CART_SUCCESS="REMOVE_PRODUCT_CART_SUCCESS";
export const REMOVE_PRODUCT_CART_FAILURE="REMOVE_PRODUCT_CART_FAILURE";

export const ADD_ORDER_REQUEST="ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS="ADD_ORDER_SUCCESS";;
export const ADD_ORDER_FAILURE="ADD_ORDER_FAILURE";

export const EMPTY_CART_REQUEST="EMPTY_CART_REQUEST";
export const EMPTY_CART_SUCCESS="EMPTY_CART_SUCCESS";
export const EMPTY_CART_FAILUER="EMPTY_CART_FAILURE";

export const FETCH_ORDERS_REQUEST="FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS="FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE="FETCH_ORDERS_FAILURE";


